config/routes.rb
Rails.application.routes.draw do

  resources :pictures

  resources :insights

  resources :backlog_items

  resources :backlogs

  resources :questions

  resources :mission_environments

  resources :environments

  resources :mission_procedures

  resources :procedures

  resources :mission_personas

  resources :personas

  resources :mission_memberships

  resources :missions

  devise_for :users
  root 'missions#index'

  resources :users

end

app/models/backlog.rb
class Backlog < ActiveRecord::Base
  belongs_to :mission
  has_many :backlog_items

  validates :mission_id, presence: true
end

app/models/backlog_item.rb
class BacklogItem < ActiveRecord::Base
  belongs_to :backlog
  belongs_to :question
  # belongs_to :assigned_to, class_name: 'User', foreign_key: 'assigned_to'

  has_many :insights, as: :insightable
  has_many :pictures, as: :pictureable

  validates :question_id, :backlog_id, presence: true
end

app/models/environment.rb
class Environment < ActiveRecord::Base
    has_many :mission_environments, dependent: :destroy
    has_many :missions, through: :mission_environments

    has_many :questions, as: :questionable

    has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/insight.rb
class Insight < ActiveRecord::Base
  belongs_to :insightable, polymorphic: true
  belongs_to :user
end

app/models/mission.rb
class Mission < ActiveRecord::Base
  validates :date, :company, :customer_point_of_contact, presence: true

  has_many :mission_memberships, dependent: :destroy
  has_many :users, through: :mission_memberships

  has_many :mission_procedures, dependent: :destroy
  has_many :procedures, through: :mission_procedures

  has_many :mission_environments, dependent: :destroy
  has_many :environments, through: :mission_environments

  has_many :questions, as: :questionable
  has_many :insights, as: :insightable

  has_one :backlog
end

app/models/mission_membership.rb
class MissionMembership < ActiveRecord::Base
  belongs_to :user
  belongs_to :mission

  validates :user_id, :mission_id, presence: true
end

app/models/mission_persona.rb
class MissionPersona < ActiveRecord::Base
  belongs_to :mission
  belongs_to :persona

  validates :mission_id, :persona_id, presence: true
end

app/models/mission_procedure.rb
class MissionProcedure < ActiveRecord::Base
  belongs_to :mission
  belongs_to :procecure

  validates :mission_id, :procedure_id, presence: true
end

app/models/persona.rb
class Persona < ActiveRecord::Base
  has_many :mission_personas, dependent: :destroy
  has_many :missions, through: :mission_personas

  has_many :questions, as: :questionable

  validates :name, :goals, presence: true

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :pictureable, polymorphic: true
  has_attached_file :image_url, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :image_url, :content_type => /\Aimage\/.*\Z/

end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
  has_many :mission_procedures, dependent: :destroy
  has_many :missions, through: :mission_procedures

  has_many :questions, as: :questionable

  validates :name, :steps, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :questionable, polymorphic: true

  # has_many :questions, as: :questionable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :mission_memberships, dependent: :destroy
  has_many :missions, through: :mission_memberships
  has_many :insights
end

app/controllers/backlogs_controller.rb
class BacklogsController < ApplicationController
  before_action :set_backlog, only: [:show, :edit, :update, :destroy]

  # GET /backlogs
  # GET /backlogs.json
  def index
    @backlogs = Backlog.all
  end

  # GET /backlogs/1
  # GET /backlogs/1.json
  def show
  end

  # GET /backlogs/new
  def new
    @backlog = Backlog.new
  end

  # GET /backlogs/1/edit
  def edit
  end

  # POST /backlogs
  # POST /backlogs.json
  def create
    @backlog = Backlog.new(backlog_params)

    respond_to do |format|
      if @backlog.save
        format.html { redirect_to @backlog, notice: 'Backlog was successfully created.' }
        format.json { render :show, status: :created, location: @backlog }
      else
        format.html { render :new }
        format.json { render json: @backlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backlogs/1
  # PATCH/PUT /backlogs/1.json
  def update
    respond_to do |format|
      if @backlog.update(backlog_params)
        format.html { redirect_to @backlog, notice: 'Backlog was successfully updated.' }
        format.json { render :show, status: :ok, location: @backlog }
      else
        format.html { render :edit }
        format.json { render json: @backlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backlogs/1
  # DELETE /backlogs/1.json
  def destroy
    @backlog.destroy
    respond_to do |format|
      format.html { redirect_to backlogs_url, notice: 'Backlog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_backlog
      @backlog = Backlog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def backlog_params
      params.require(:backlog).permit(:mission_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backlogs_helper.rb
module BacklogsHelper
end

app/helpers/insights_helper.rb
module InsightsHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/backlogs/_form.html.erb
<%= form_for(@backlog, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @backlog.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@backlog.errors.count, "error") %> prohibited this backlog from being saved:</h4>

      <ul>
      <% @backlog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :mission_id, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select :mission_id, Mission.all, :id, :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/backlogs/edit.html.erb
<div class="page-header">
  <%= link_to backlogs_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @backlog, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing backlog</h1>
</div>

<%= render 'form' %>

app/views/backlogs/index.html.erb
<div class="page-header">
  <h1>
    Backlogs
    <%= link_to icon('plus'), new_backlog_path, class: "btn btn-lg btn-success" %>
  </h1>
</div>

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Backlogs (start typing)" class="form-control">
  </div>
</div>

<hr>

<div class="row isotope-container">
<% @backlogs.each do |backlog| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Backlog #<%= backlog.id %></h3>
      </div>
      <div class="panel-body">
        <dl>
          <dt>Mission</dt>
          <dd><%= backlog.mission_id %></dd>

        </dl>
        <div class="btn-group btn-group-justified">
          <%= link_to icon('search-plus'), backlog, class: "btn btn-primary" %>

          <%= link_to icon('edit'), edit_backlog_url(backlog), class: "btn btn-warning" %>

          <%= link_to icon('trash-o'), backlog, method: :delete, data: { confirm: "Do you really want to delete this backlog?" }, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;
    // init Isotope
    var $container = $('.isotope-container');
    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });
    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );
  });
  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/backlogs/new.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">New Backlog</h3>
      </div>
      <div class="panel-body">
        <%= render 'form', backlog: @backlog %>
      </div>
    </div>
  </div>
</div>

app/views/backlogs/show.html.erb
<div class="page-header">
  <%= link_to backlogs_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_backlog_path(@backlog), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show backlog</h1>
</div>

<dl class="dl-horizontal">
  <dt>Mission:</dt>
  <dd><%= @backlog.mission_id %></dd>

</dl>