config/routes.rb
Rails.application.routes.draw do

  resources :pictures

  resources :insights

  resources :backlog_items

  resources :backlogs

  resources :questions

  resources :mission_environments

  resources :environments

  resources :mission_procedures

  resources :procedures

  resources :mission_personas

  resources :personas

  resources :mission_memberships

  resources :missions

  devise_for :users
  root 'missions#index'

  resources :users

end

app/models/backlog.rb
class Backlog < ActiveRecord::Base
  belongs_to :mission
  has_many :backlog_items

  validates :mission_id, presence: true
end

app/models/backlog_item.rb
class BacklogItem < ActiveRecord::Base
  belongs_to :backlog
  belongs_to :question
  # belongs_to :assigned_to, class_name: 'User', foreign_key: 'assigned_to'

  has_many :insights, as: :insightable
  has_many :pictures, as: :pictureable

  validates :question_id, :backlog_id, presence: true
end

app/models/environment.rb
class Environment < ActiveRecord::Base
    has_many :mission_environments, dependent: :destroy
    has_many :missions, through: :mission_environments

    has_many :questions, as: :questionable

    has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/insight.rb
class Insight < ActiveRecord::Base
  belongs_to :insightable, polymorphic: true
  belongs_to :user
end

app/models/mission.rb
class Mission < ActiveRecord::Base
  validates :date, :company, :customer_point_of_contact, presence: true

  has_many :mission_memberships, dependent: :destroy
  has_many :users, through: :mission_memberships

  has_many :mission_procedures, dependent: :destroy
  has_many :procedures, through: :mission_procedures

  has_many :mission_environments, dependent: :destroy
  has_many :environments, through: :mission_environments

  has_many :questions, as: :questionable
  has_many :insights, as: :insightable

  has_one :backlog
end

app/models/mission_membership.rb
class MissionMembership < ActiveRecord::Base
  belongs_to :user
  belongs_to :mission

  validates :user_id, :mission_id, presence: true
end

app/models/mission_persona.rb
class MissionPersona < ActiveRecord::Base
  belongs_to :mission
  belongs_to :persona

  validates :mission_id, :persona_id, presence: true
end

app/models/mission_procedure.rb
class MissionProcedure < ActiveRecord::Base
  belongs_to :mission
  belongs_to :procecure

  validates :mission_id, :procedure_id, presence: true
end

app/models/persona.rb
class Persona < ActiveRecord::Base
  has_many :mission_personas, dependent: :destroy
  has_many :missions, through: :mission_personas

  has_many :questions, as: :questionable

  validates :name, :goals, presence: true

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :pictureable, polymorphic: true
  has_attached_file :image_url, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :image_url, :content_type => /\Aimage\/.*\Z/

end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
  has_many :mission_procedures, dependent: :destroy
  has_many :missions, through: :mission_procedures

  has_many :questions, as: :questionable

  validates :name, :steps, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :questionable, polymorphic: true

  # has_many :questions, as: :questionable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :mission_memberships, dependent: :destroy
  has_many :missions, through: :mission_memberships
  has_many :insights
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :set_mission, only: [:show, :edit, :update, :destroy]

  # GET /missions
  # GET /missions.json
  def index
    @missions = Mission.all
  end

  # GET /missions/1
  # GET /missions/1.json
  def show
    @question = @mission.questions.build
    @insight = @mission.insights.build
    @environment = Environment.new
  end

  # GET /missions/new
  def new
    @mission = Mission.new
  end

  # GET /missions/1/edit
  def edit
  end

  # POST /missions
  # POST /missions.json
  def create
    @mission = Mission.new(mission_params)

    respond_to do |format|
      if @mission.save
        format.html { redirect_to @mission, notice: 'Mission was successfully created.' }
        format.json { render :show, status: :created, location: @mission }
      else
        format.html { render :new }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /missions/1
  # PATCH/PUT /missions/1.json
  def update
    respond_to do |format|
      if @mission.update(mission_params)
        format.html { redirect_to @mission, notice: 'Mission was successfully updated.' }
        format.json { render :show, status: :ok, location: @mission }
      else
        format.html { render :edit }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /missions/1
  # DELETE /missions/1.json
  def destroy
    @mission.destroy
    respond_to do |format|
      format.html { redirect_to missions_url, notice: 'Mission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mission
      @mission = Mission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mission_params
      params.require(:mission).permit(:date, :company, :customer_point_of_contact, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backlogs_helper.rb
module BacklogsHelper
end

app/helpers/insights_helper.rb
module InsightsHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/missions/_form.html.erb
<%= form_for(@mission, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @mission.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@mission.errors.count, "error") %> prohibited this mission from being saved:</h4>

      <ul>
      <% @mission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :date, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :company, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :company, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :customer_point_of_contact, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :customer_point_of_contact, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/missions/edit.html.erb
<div class="page-header">
  <%= link_to missions_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @mission, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing mission</h1>
</div>

<%= render 'form' %>

app/views/missions/index.html.erb
<div class="page-header">
  <h1>
    Missions
    <%= link_to icon('plus'), new_mission_path, class: "btn btn-lg btn-success" %>
  </h1>
</div>

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Missions (start typing)" class="form-control">
  </div>
</div>

<hr>

<div class="row isotope-container">
<% @missions.each do |mission| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Mission #<%= mission.id %></h3>
      </div>
      <div class="panel-body">
        <dl>
          <dt>Name</dt>
          <dd><%= mission.name %></dd>

          <dt>Date</dt>
          <dd><%= mission.date %></dd>

          <dt>Company</dt>
          <dd><%= mission.company %></dd>

          <dt>Customer point of contact</dt>
          <dd><%= mission.customer_point_of_contact %></dd>

        </dl>
        <div class="btn-group btn-group-justified">
          <%= link_to icon('search-plus'), mission, class: "btn btn-primary" %>

          <%= link_to icon('edit'), edit_mission_url(mission), class: "btn btn-warning" %>

          <%= link_to icon('trash-o'), mission, method: :delete, data: { confirm: "Do you really want to delete this mission?" }, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;
    // init Isotope
    var $container = $('.isotope-container');
    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });
    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );
  });
  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/missions/new.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">New Mission</h3>
      </div>
      <div class="panel-body">
        <%= render 'form', mission: @mission %>
      </div>
    </div>
  </div>
</div>

app/views/missions/show.html.erb
<div class="page-header">
  <%= link_to missions_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_mission_path(@mission), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>
    <%= @mission.name %>
    <small><%= @mission.date %> - <%= @mission.company %></small>
  </h1>
  <div><strong>Contact:</strong> <%= @mission.customer_point_of_contact %></div>
</div>
<div class="row">
  <div class="col-md-6">
    <h2>Backlog</h2>

    <ul class="list-group">
      <% @mission.backlog.backlog_items.each do |item| %>
        <li class="list-group-item">
          <div>
            <h3><%= item.question.contents %></h3>
            <div class="pull-right">
              <a href="/pictures/new?backlog_item_id=<%= item.id %>">add a picture</a>
            </div>
          </div>
          <div>Assigned to: <%= User.find(item.assigned_to).name %></div>
          <div>
            <%= link_to "edit", edit_backlog_item_path(item)  %> |
            <%= link_to "destroy", item, method: :delete  %>
          </div>
          <div class="row">
            <% item.pictures.each do |picture| %>
              <div class="col-md-3"><%= link_to image_tag(picture.image_url.url, class: 'img-responsive'), picture %></div>
            <% end %>
          </div>
          <h4>Insights</h4>
          <ul class="list-group">
            <% item.insights.each do |insight| %>
              <li class="list-group-item">
                <strong><%= insight.user.name %>:</strong> <%= insight.contents %>
                <div>
                  <%= link_to "edit", edit_insight_path(insight)  %> |
                  <%= link_to "destroy", insight, method: :delete  %>
                </div>
              </li>
            <% end %>
          </ul>
          <div class="row">
            <div class="col-md-12">
              <h4>Add an insight:</h4>
              <% insight = item.insights.build %>
              <%= form_for insight do |f| -%>
                <% if @question.errors.any? %>
                  <div class="alert alert-danger alert-dismissable" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h5><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h5>

                    <ul>
                    <% @question.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                    </ul>

                  </div>
                <% end %>
                <%= f.hidden_field :insightable_id, :class => "form-control" %>
                <%= f.hidden_field :insightable_type, :class => "form-control" %>
                <%= f.hidden_field :user_id, value: current_user.id, :class => "form-control" %>
                <div class="form-group">
                  <%= f.label :contents, :class => "control-label sr-only" %>
                  <%= f.text_field :contents, :class => "form-control", placeholder: "What was your aha?" %>
                </div>
              <% end -%>
            </div>
          </div>
        </li>
      <% end %>
    </ul>

  </div>
  <div class="col-md-6">

    <h3>Add new question to the Backlog</h3>
    <%= form_for(@question, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
      <% if @question.errors.any? %>
        <div class="alert alert-danger alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h4>

          <ul>
          <% @question.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :contents, :class => "control-label sr-only" %>
        <div class="col-sm-10">
          <%= f.text_field :contents, :class => "form-control" %>
        </div>
      </div>
      <%= f.hidden_field :questionable_id, value: @question.questionable_id, :class => "form-control" %>
      <%= f.hidden_field :questionable_type, value: @question.questionable_type, :class => "form-control" %>
      <%= f.fields_for :backlog_item do |backlog_item_fields| %>
          <%= backlog_item_fields.hidden_field :backlog_id, value: @mission.backlog.id %>
          <%= backlog_item_fields.hidden_field :assigned_to, value: current_user.id %>
          <div class="form-group">
              <div class="col-sm-10">
              <label for="assigned_to">Assigned to:</label>
                <%= backlog_item_fields.collection_select :assigned_to, User.all, :id, :name, :class => "form-control" %>
              </div>
          </div>
        <% end %>
      <div class="form-group">
        <div class="col-sm-10">
          <%= f.submit :class => "btn btn-primary" %>
        </div>
      </div>
    <% end %>
    <h2>- or -</h2>
    <h3>Add an existing question to the backlog</h3>
    <%= form_for(BacklogItem.new, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
      <% if @question.errors.any? %>
        <div class="alert alert-danger alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h4>

          <ul>
          <% @question.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

          <%= f.hidden_field :backlog_id, value: @mission.backlog.id, :class => "form-control" %>
      <div class="form-group">
          <div class="col-sm-10">
            <%= f.collection_select :question_id, Question.all, :id, :contents, :class => "form-control" %>
          </div>
      </div>
      <div class="form-group">
          <div class="col-sm-10">
          <label for="assigned_to">Assigned to:</label>
            <%= f.collection_select :assigned_to, User.all, :id, :name, :class => "form-control" %>
          </div>
      </div>
      <div class="form-group">

        <div class="col-sm-10">
          <%= f.submit :class => "btn btn-primary" %>
        </div>
      </div>
    <% end %>


  </div>
</div>

<!-- <div class="row">
  <div class="col-md-4">
    <h2>Environments</h2>

      <h3>Add a new environment</h3>
      <%= form_for(@environment, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
        <% if @environment.errors.any? %>
          <div class="alert alert-danger alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4><%= pluralize(@environment.errors.count, "error") %> prohibited this environment from being saved:</h4>

            <ul>
            <% @environment.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :name, :class => "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :name, :class => "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :desc, :class => "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_area :desc, :class => "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :image, :class => "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.file_field :image %>
          </div>
        </div>
          <%#= f.fields_for :backlog_item do |backlog_item_fields| %>
            <%#= backlog_item_fields.hidden_field :backlog_id, value: @mission.backlog.id %>
            <%#= backlog_item_fields.hidden_field :assigned_to, value: current_user.id %>
            <div class="form-group">
                <div class="col-sm-10">
                <label for="assigned_to">Assigned to:</label>
                  <%#= backlog_item_fields.collection_select :assigned_to, User.all, :id, :name, :class => "form-control" %>
                </div>
            </div>
          <%# end %>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%#= f.submit :class => "btn btn-primary" %>
          </div>
        </div>
      <% end %>

  </div>
  <div class="col-md-4">
    <h2>Personas</h2>
  </div>
  <div>
    <h2>Procedures</h2>
  </div>
</div> -->